version: "2.3"

services:
    front:
        build: ./front
        image: "front-end"
        restart: always
        ports:
            - "8081:80"
        expose:
            - "80"
    back:
        build: ./back
        image: "back-end"
        ports:
            - "4000:4000"
        expose:
            - "4000"
        restart: always
        # Not used in the index.js
        # environment:
        #     POSTGRES_USER: 'postgres'
        #     POSTGRES_PASSWORD: 'pgadmin'
        depends_on:
            - db

    db:
        image: postgres
        ports:
            - "5432:5432"
        expose:
            - "5432"
        restart: always
        environment:
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'pgadmin'
        volumes:
            - "db-data:/var/lib/postgresql/data"

volumes:
    db-data:
